# sources.yml
schema_version: "1.0"
mcp_name: "Philippine Law MCP"
jurisdiction: "PH"

sources:
  - name: "Philippine Laws and Jurisprudence Databank (LawPhil)"
    authority: "LawPhil Project / Arellano Law Foundation"
    official_portal: "https://lawphil.net"
    canonical_identifier: "Republic Act number (e.g., 'RA 10173'), Act number (e.g., 'Act No. 3815')"
    retrieval_method: "HTML_SCRAPE"
    api_documentation: "N/A (structured web interface with comprehensive legislation database)"
    update_frequency: "weekly"
    last_ingested: "2026-02-26"
    license_or_terms:
      type: "Open Access"
      url: "https://lawphil.net"
      summary: "LawPhil is the most comprehensive free online database of Philippine laws; maintained by the Arellano Law Foundation under Creative Commons Attribution-NonCommercial 4.0; legislation text is government work product"
    coverage:
      scope: "11,600+ Republic Acts (RA 1 from 1946 to RA 12036 from 2024), the 1987 Constitution, and the Revised Penal Code (Act No. 3815). Census-first full corpus ingestion."
      limitations: "Some very recently enacted laws may have a delay before appearing; Implementing Rules and Regulations (IRR) not systematically included; Presidential Decrees, Executive Orders, and Batas Pambansa not yet covered in this release"
    languages:
      - "en"

  - name: "Official Gazette of the Republic of the Philippines"
    authority: "Office of the President, Republic of the Philippines"
    official_portal: "https://www.officialgazette.gov.ph"
    canonical_identifier: "N/A"
    retrieval_method: "HTML_SCRAPE"
    api_documentation: "N/A"
    update_frequency: "weekly"
    last_ingested: "SUPPLEMENTARY_SOURCE"
    license_or_terms:
      type: "Government Open Data"
      url: "https://www.officialgazette.gov.ph"
      summary: "Official publication of the Republic of the Philippines; laws take effect 15 days after publication in the Official Gazette or in a newspaper of general circulation unless otherwise provided"
    coverage:
      scope: "Newly enacted Republic Acts, Executive Orders, Presidential Proclamations, and Administrative Orders"
      limitations: "Used as supplementary reference; primary ingestion is from LawPhil"
    languages:
      - "en"
      - "fil"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-26"

# Notes:
# - The Philippines uses a mixed legal system combining civil law (Spanish heritage) and
#   common law (American heritage) with elements of customary and Islamic law (in Bangsamoro)
# - The 1987 Constitution is the supreme law; Article III Section 3 protects the privacy
#   of communication and correspondence
# - The Data Privacy Act 2012 (RA 10173) is the comprehensive data protection law; the
#   National Privacy Commission (NPC) is one of the most active DPAs in Asia
# - RA 10175 (Cybercrime Prevention Act 2012) covers cyber offences, online libel, and
#   law enforcement powers for cybercrime
# - RA 11934 (SIM Registration Act 2022) requires registration of all SIM cards with
#   data privacy implications
# - The Philippines uses Republic Act (RA) numbering for legislation passed by Congress
# - Legislation is primarily in English, which is one of the two official languages
#   (with Filipino); English is the primary language of law and courts
# - The NPC has been actively pursuing EU GDPR adequacy status
# - The Philippines is an ASEAN member and participates in ASEAN data governance frameworks
# - Population of 110M+; rapidly growing digital economy
# - Implementing Rules and Regulations (IRR) are issued for most major laws
# - Census approach: scrape the main Republic Acts index page at lawphil.net/statutes/repacts/
#   which lists all 11,600+ Republic Acts in a single HTML table
