#!/usr/bin/env tsx
/**
 * Philippine Law MCP — Ingestion Pipeline
 *
 * Fetches Philippine legislation from LawPhil (lawphil.net).
 * LawPhil is the most comprehensive free Philippine law database,
 * maintained by the Arellano Law Foundation.
 *
 * **Census-driven**: Reads data/census.json (generated by scripts/census.ts) to
 * enumerate ALL Republic Acts. Falls back to KEY_PHILIPPINE_ACTS if census is missing.
 *
 * Usage:
 *   npm run ingest                    # Full ingestion (from census)
 *   npm run ingest -- --limit 5       # Test with 5 acts
 *   npm run ingest -- --skip-fetch    # Reuse cached HTML
 *   npm run ingest -- --resume        # Skip acts that already have seed files
 *
 * Data source: lawphil.net (Arellano Law Foundation)
 * Format: HTML (well-structured, English text)
 * License: Open Access (government work product)
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { fetchWithRateLimit } from './lib/fetcher.js';
import {
  parsePhilippineHtml,
  KEY_PHILIPPINE_ACTS,
  type ActIndexEntry,
  type ParsedAct,
} from './lib/parser.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SOURCE_DIR = path.resolve(__dirname, '../data/source');
const SEED_DIR = path.resolve(__dirname, '../data/seed');
const CENSUS_PATH = path.resolve(__dirname, '../data/census.json');

// Maximum concurrency for fetching (be respectful to lawphil.net)
const MAX_CONCURRENT = 3;

interface CensusLaw {
  id: string;
  raNumber: number;
  year: number;
  title: string;
  date: string;
  url: string;
  category: 'republic_act' | 'constitution' | 'act';
  classification: 'ingestable' | 'inaccessible' | 'metadata_only';
}

interface CensusData {
  generated_at: string;
  stats: {
    total: number;
    class_ingestable: number;
    class_inaccessible: number;
    class_metadata_only: number;
  };
  ingestion?: {
    completed_at: string;
    total_laws: number;
    total_provisions: number;
    coverage_pct: string;
  };
  laws: CensusLaw[];
}

function parseArgs(): { limit: number | null; skipFetch: boolean; resume: boolean } {
  const args = process.argv.slice(2);
  let limit: number | null = null;
  let skipFetch = false;
  let resume = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--limit' && args[i + 1]) {
      limit = parseInt(args[i + 1], 10);
      i++;
    } else if (args[i] === '--skip-fetch') {
      skipFetch = true;
    } else if (args[i] === '--resume') {
      resume = true;
    }
  }

  return { limit, skipFetch, resume };
}

/**
 * Convert a census law entry into the ActIndexEntry format used by the parser.
 */
function censusLawToIndexEntry(law: CensusLaw): ActIndexEntry {
  // Generate short name from RA number or special category
  let shortName: string;
  if (law.category === 'republic_act') {
    shortName = `RA ${law.raNumber}`;
  } else if (law.category === 'constitution') {
    shortName = '1987 Constitution';
  } else {
    shortName = `Act No. ${law.raNumber || law.id}`;
  }

  return {
    id: law.id,
    title: law.title,
    titleEn: law.title, // Philippine laws are in English
    shortName,
    status: 'in_force',
    issuedDate: law.date,
    inForceDate: law.date,
    url: law.url,
  };
}

/**
 * Load acts from census.json if available, otherwise fall back to KEY_PHILIPPINE_ACTS.
 */
function loadActList(): ActIndexEntry[] {
  if (fs.existsSync(CENSUS_PATH)) {
    const raw = fs.readFileSync(CENSUS_PATH, 'utf-8');
    const census = JSON.parse(raw) as CensusData;

    console.log(`  Census: ${census.stats.total} laws (generated ${census.generated_at})`);

    // Only include ingestable laws
    const ingestable = census.laws.filter(l => l.classification === 'ingestable');
    console.log(`  Ingestable: ${ingestable.length} laws`);

    return ingestable.map(censusLawToIndexEntry);
  }

  console.log('  WARNING: No census.json found — falling back to KEY_PHILIPPINE_ACTS (10 acts)');
  console.log('  Run: npx tsx scripts/census.ts   to generate full census\n');
  return KEY_PHILIPPINE_ACTS;
}

/**
 * Create a metadata-only seed file when fetching/parsing fails.
 */
function createFallbackSeed(act: ActIndexEntry): ParsedAct {
  return {
    id: act.id,
    type: 'statute',
    title: act.title,
    title_en: act.titleEn,
    short_name: act.shortName,
    status: act.status,
    issued_date: act.issuedDate,
    in_force_date: act.inForceDate,
    url: act.url,
    provisions: [],
    definitions: [],
  };
}

async function fetchAndParseActs(
  acts: ActIndexEntry[],
  skipFetch: boolean,
  resume: boolean,
): Promise<void> {
  console.log(`\nProcessing ${acts.length} Philippine laws from lawphil.net...\n`);

  fs.mkdirSync(SOURCE_DIR, { recursive: true });
  fs.mkdirSync(SEED_DIR, { recursive: true });

  let processed = 0;
  let resumed = 0;
  let skipped = 0;
  let failed = 0;
  let httpErrors = 0;
  let totalProvisions = 0;
  let totalDefinitions = 0;
  const startTime = Date.now();

  const report: { act: string; provisions: number; definitions: number; status: string }[] = [];

  for (const act of acts) {
    const sourceFile = path.join(SOURCE_DIR, `${act.id}.html`);
    const seedFile = path.join(SEED_DIR, `${act.id}.json`);

    // Resume support: skip acts that already have seed files
    if (resume && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
        totalProvisions += existing.provisions?.length ?? 0;
        totalDefinitions += existing.definitions?.length ?? 0;
      } catch {
        // Corrupted seed file, re-process
      }
      resumed++;
      processed++;
      continue;
    }

    // Skip if seed already exists and we're in skip-fetch mode
    if (skipFetch && fs.existsSync(seedFile)) {
      const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
      totalProvisions += existing.provisions?.length ?? 0;
      totalDefinitions += existing.definitions?.length ?? 0;
      report.push({
        act: act.shortName,
        provisions: existing.provisions?.length ?? 0,
        definitions: existing.definitions?.length ?? 0,
        status: 'cached',
      });
      skipped++;
      processed++;
      continue;
    }

    try {
      let html: string;

      if (fs.existsSync(sourceFile) && skipFetch) {
        html = fs.readFileSync(sourceFile, 'utf-8');
        console.log(`  Using cached ${act.shortName} (${act.id})`);
      } else {
        process.stdout.write(`  [${processed + 1}/${acts.length}] Fetching ${act.shortName} (${act.id})...`);

        try {
          const result = await fetchWithRateLimit(act.url);

          if (result.status !== 200) {
            console.log(` HTTP ${result.status}`);
            const fallback = createFallbackSeed(act);
            fs.writeFileSync(seedFile, JSON.stringify(fallback, null, 2));
            report.push({
              act: act.shortName,
              provisions: 0,
              definitions: 0,
              status: `HTTP ${result.status}`,
            });
            httpErrors++;
            failed++;
            processed++;
            continue;
          }

          html = result.body;
          fs.writeFileSync(sourceFile, html);
          console.log(` OK (${(html.length / 1024).toFixed(0)} KB)`);
        } catch (fetchError) {
          const msg = fetchError instanceof Error ? fetchError.message : String(fetchError);
          console.log(` FETCH FAILED: ${msg}`);
          const fallback = createFallbackSeed(act);
          fs.writeFileSync(seedFile, JSON.stringify(fallback, null, 2));
          report.push({
            act: act.shortName,
            provisions: 0,
            definitions: 0,
            status: `FETCH FAILED`,
          });
          failed++;
          processed++;
          continue;
        }
      }

      const parsed = parsePhilippineHtml(html, act);
      fs.writeFileSync(seedFile, JSON.stringify(parsed, null, 2));

      totalProvisions += parsed.provisions.length;
      totalDefinitions += parsed.definitions.length;

      report.push({
        act: act.shortName,
        provisions: parsed.provisions.length,
        definitions: parsed.definitions.length,
        status: 'OK',
      });

      console.log(`    -> ${parsed.provisions.length} provisions, ${parsed.definitions.length} definitions`);
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      console.log(`  ERROR parsing ${act.shortName}: ${msg}`);
      const fallback = createFallbackSeed(act);
      fs.writeFileSync(seedFile, JSON.stringify(fallback, null, 2));
      report.push({
        act: act.shortName,
        provisions: 0,
        definitions: 0,
        status: `ERROR: ${msg.substring(0, 60)}`,
      });
      failed++;
    }

    processed++;

    // Progress log every 50 acts
    if (processed % 50 === 0) {
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(0);
      const rate = (processed / ((Date.now() - startTime) / 1000)).toFixed(1);
      const eta = ((Date.now() - startTime) / processed * (acts.length - processed) / 1000).toFixed(0);
      console.log(`\n  --- Progress: ${processed}/${acts.length} (${elapsed}s elapsed, ${rate} acts/s, ~${eta}s remaining) ---\n`);
    }
  }

  const totalElapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  // Print summary report
  console.log(`\n${'='.repeat(70)}`);
  console.log('INGESTION REPORT');
  console.log('='.repeat(70));

  if (report.length <= 100) {
    console.log(`\n${'Act'.padEnd(30)} ${'Prov'.padEnd(8)} ${'Defs'.padEnd(8)} Status`);
    console.log('-'.repeat(70));
    for (const r of report) {
      console.log(
        `${r.act.substring(0, 29).padEnd(30)} ${String(r.provisions).padEnd(8)} ${String(r.definitions).padEnd(8)} ${r.status}`
      );
    }
    console.log('-'.repeat(70));
  } else {
    const okCount = report.filter(r => r.status === 'OK').length;
    const failedCount = report.filter(r => !['OK', 'cached'].includes(r.status)).length;
    const cachedCount = report.filter(r => r.status === 'cached').length;
    console.log(`\n  New ingestions:  ${okCount}`);
    console.log(`  Cached:          ${cachedCount}`);
    console.log(`  Failed:          ${failedCount}`);
    if (failedCount > 0 && failedCount <= 50) {
      console.log('\n  Failed acts:');
      for (const r of report.filter(r => !['OK', 'cached'].includes(r.status))) {
        console.log(`    ${r.act.substring(0, 39).padEnd(40)} ${r.status}`);
      }
    }
  }

  console.log(`\n${'='.repeat(70)}`);
  console.log(`  Source:            lawphil.net (Arellano Law Foundation)`);
  console.log(`  License:           Open Access (government work product)`);
  console.log(`  Total elapsed:     ${totalElapsed}s`);
  console.log(`  Acts processed:    ${processed}`);
  console.log(`  Acts resumed:      ${resumed}`);
  console.log(`  Acts cached:       ${skipped}`);
  console.log(`  Acts failed:       ${failed} (${httpErrors} HTTP errors)`);
  console.log(`  Total provisions:  ${totalProvisions}`);
  console.log(`  Total definitions: ${totalDefinitions}`);

  // Update census.json with ingestion stats
  if (fs.existsSync(CENSUS_PATH)) {
    const census = JSON.parse(fs.readFileSync(CENSUS_PATH, 'utf-8'));
    census.ingestion = {
      completed_at: new Date().toISOString(),
      total_laws: processed - failed,
      total_provisions: totalProvisions,
      coverage_pct: ((processed - failed) / acts.length * 100).toFixed(1),
    };

    // Update classification for HTTP error acts
    if (httpErrors > 0) {
      for (const fr of report.filter(r => r.status.startsWith('HTTP'))) {
        const censusLaw = census.laws.find((a: CensusLaw) =>
          a.id === acts.find(act => act.shortName === fr.act)?.id
        );
        if (censusLaw) {
          censusLaw.classification = 'inaccessible';
        }
      }
      census.stats.class_ingestable = census.laws.filter((a: CensusLaw) => a.classification === 'ingestable').length;
      census.stats.class_inaccessible = census.laws.filter((a: CensusLaw) => a.classification === 'inaccessible').length;
    }

    fs.writeFileSync(CENSUS_PATH, JSON.stringify(census, null, 2) + '\n');
    console.log(`\n  Updated census.json with ingestion stats.`);
  }
}

async function main(): Promise<void> {
  const { limit, skipFetch, resume } = parseArgs();

  console.log('Philippine Law MCP -- Ingestion Pipeline');
  console.log('========================================\n');
  console.log(`  Source: LawPhil (lawphil.net)`);
  console.log(`  Maintainer: Arellano Law Foundation`);
  console.log(`  Format: HTML (English text)`);
  console.log(`  Rate limit: 500ms between requests`);

  if (limit) console.log(`  --limit ${limit}`);
  if (skipFetch) console.log(`  --skip-fetch`);
  if (resume) console.log(`  --resume (skip existing seed files)`);

  const allActs = loadActList();
  const acts = limit ? allActs.slice(0, limit) : allActs;
  await fetchAndParseActs(acts, skipFetch, resume);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
